# Site settings
title: Data Science in Libraries
email: info@datascienceinlibraries.org
description: > # this means to ignore newlines until "baseurl:"
  Data Science in Libaries is made possible by the Institute of Museum and Library Services grant number RE-43-16-0149-16.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://datascienceinlibaries.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  datascienceinlibraries

# Build settings
markdown: kramdown

theme: minima
